controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login:
  path: /login
  controller: App\Controller\LoginController::login

login_callback:
  path: /login/google/callback
  controller: App\Controller\LoginController::loginCallback

login_with_google:
  path: /login/google
  controller: App\Controller\LoginController::loginWithGoogle

home:
  path: /home
  controller: App\Controller\HomeController::index
  methods: GET

video_detail:
    path: '/videos/{videoId}'
    controller: App\Controller\HomeController::videoDetail

video_code:
    path: '/code/{videoId}'
    controller: App\Controller\HomeController::videoCode

enable_eloqua:
    path: '/enable'
    controller: App\Controller\EloquaController::enableEloqua

uninstall_eloqua:
    path: '/uninstall'
    controller: App\Controller\EloquaController::uninstallEloqua

oauth_eloqua:
    path: '/eloquaoauth'
    controller: App\Controller\EloquaController::eloquaOauth

create_instance_eloqua:
    path: '/createInstance'
    controller: App\Controller\EloquaContentController::createInstance

delete_instance_eloqua:
    path: '/deleteInstance'
    controller: App\Controller\EloquaContentController::deleteInstance

copy_instance_eloqua:
    path: '/copyInstance'
    controller: App\Controller\EloquaContentController::copyInstance

notification_instance_eloqua:
    path: '/notificationLandingPage'
    controller: App\Controller\EloquaContentController::notificationLandingPage


